"""Cambio de relacion para profiles eating style a N M

Revision ID: 13ae56e473fb
Revises: 5e77f13f4638
Create Date: 2026-02-20 16:19:54.900026

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '13ae56e473fb'
down_revision = '5e77f13f4638'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eating_styles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eating_styles_id'), 'eating_styles', ['id'], unique=False)
    op.create_table('profiles_eating_styles',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('eating_style_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['eating_style_id'], ['eating_styles.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'eating_style_id')
    )
    op.drop_index(op.f('ix_profile_eating_styles_id'), table_name='profile_eating_styles')
    op.drop_index(op.f('ix_profile_eating_styles_profile_id'), table_name='profile_eating_styles')
    op.drop_table('profile_eating_styles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_eating_styles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', postgresql.ENUM('high_protein', 'low_carb', 'vegan', 'vegetarian', 'low_calorie', 'high_fiber', 'high_carb', name='eating_style_enum'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('profile_eating_styles_profile_id_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('profile_eating_styles_pkey'))
    )
    op.create_index(op.f('ix_profile_eating_styles_profile_id'), 'profile_eating_styles', ['profile_id'], unique=False)
    op.create_index(op.f('ix_profile_eating_styles_id'), 'profile_eating_styles', ['id'], unique=False)
    op.drop_table('profiles_eating_styles')
    op.drop_index(op.f('ix_eating_styles_id'), table_name='eating_styles')
    op.drop_table('eating_styles')
    # ### end Alembic commands ###
