"""cambio de tipos en profile

Revision ID: 1e6279aa4b4a
Revises: 13ae56e473fb
Create Date: 2026-02-21 16:15:15.129316

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '1e6279aa4b4a'
down_revision = '13ae56e473fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Creamos el objeto del tipo Enum
    body_type_enum = postgresql.ENUM('lean', 'normal', 'stocky', 'obese', name='body_type_enum')
    
    # 2. Le pedimos a Postgres que lo cree físicamente en la DB
    body_type_enum.create(op.get_bind(), checkfirst=True)

    # 3. Ahora sí, añadimos la columna usando ese tipo
    op.add_column('profiles', sa.Column('body_type', sa.Enum('lean', 'normal', 'stocky', 'obese', name='body_type_enum'), nullable=True))

    op.alter_column('profiles', 'height',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('profiles', 'weight',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('profiles', 'body_fat_percentage',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('profiles', 'calories_target',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('profiles', 'protein_target',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('profiles', 'carbs_target',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('profiles', 'fat_target',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'fat_target',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('profiles', 'carbs_target',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('profiles', 'protein_target',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('profiles', 'calories_target',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('profiles', 'body_fat_percentage',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('profiles', 'weight',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('profiles', 'height',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.drop_column('profiles', 'body_type')

    # Borramos el tipo de la base de datos
    body_type_enum = postgresql.ENUM(name='body_type_enum')
    body_type_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
