"""actualizar campos not null

Revision ID: 5be19c140069
Revises: a4aa79125a09
Create Date: 2026-02-22 10:30:10.977329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5be19c140069'
down_revision = 'a4aa79125a09'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('diet_types', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('meal_details', 'schedule',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.alter_column('meal_types', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meal_types', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('meal_details', 'schedule',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.alter_column('diet_types', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
