"""Initial migration

Revision ID: 6daad6cf0cda
Revises: 
Create Date: 2026-02-19 12:17:19.159657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6daad6cf0cda'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('protein', sa.Integer(), nullable=True),
    sa.Column('carbs', sa.Integer(), nullable=True),
    sa.Column('fat', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('recipe_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipes_id'), 'recipes', ['id'], unique=False)
    op.create_table('restrictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restrictions_id'), 'restrictions', ['id'], unique=False)
    op.create_table('tastes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tastes_id'), 'tastes', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('profile_picture_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    op.create_index(op.f('ix_plans_user_id'), 'plans', ['user_id'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal', sa.Enum('lose_weight', 'maintain_weight', 'gain_weight', name='goal_enum'), nullable=True),
    sa.Column('height', sa.DECIMAL(), nullable=True),
    sa.Column('weight', sa.DECIMAL(), nullable=True),
    sa.Column('body_fat_percentage', sa.Integer(), nullable=True),
    sa.Column('calories_target', sa.Integer(), nullable=True),
    sa.Column('protein_target', sa.Integer(), nullable=True),
    sa.Column('carbs_target', sa.Integer(), nullable=True),
    sa.Column('fat_target', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('meals_per_day', sa.SmallInteger(), nullable=True),
    sa.Column('activity_level', sa.Enum('low', 'medium', 'high', name='activity_level_enum'), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=True)
    op.create_table('recipe_diet_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('high_protein', 'low_carb', 'vegan', 'vegetarian', 'low_calorie', 'high_fiber', 'high_carb', name='diet_type_enum'), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_diet_types_id'), 'recipe_diet_types', ['id'], unique=False)
    op.create_index(op.f('ix_recipe_diet_types_recipe_id'), 'recipe_diet_types', ['recipe_id'], unique=False)
    op.create_table('recipe_meal_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('breakfast', 'lunch', 'dinner', 'snack', name='meal_type_enum'), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_meal_types_id'), 'recipe_meal_types', ['id'], unique=False)
    op.create_index(op.f('ix_recipe_meal_types_recipe_id'), 'recipe_meal_types', ['recipe_id'], unique=False)
    op.create_table('daily_menus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_menus_id'), 'daily_menus', ['id'], unique=False)
    op.create_index(op.f('ix_daily_menus_plan_id'), 'daily_menus', ['plan_id'], unique=False)
    op.create_table('profile_eating_styles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('high_protein', 'low_carb', 'vegan', 'vegetarian', 'low_calorie', 'high_fiber', 'high_carb', name='eating_style_enum'), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_eating_styles_id'), 'profile_eating_styles', ['id'], unique=False)
    op.create_index(op.f('ix_profile_eating_styles_profile_id'), 'profile_eating_styles', ['profile_id'], unique=False)
    op.create_table('profiles_restrictions',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('restriction_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restriction_id'], ['restrictions.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'restriction_id')
    )
    op.create_table('profiles_tastes',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('taste_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['taste_id'], ['tastes.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'taste_id')
    )
    op.create_table('meal_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('daily_menu_id', sa.Integer(), nullable=False),
    sa.Column('schedule', sa.Time(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('meal_type', sa.Enum('breakfast', 'lunch', 'dinner', 'snack', name='meal_type_enum'), nullable=True),
    sa.ForeignKeyConstraint(['daily_menu_id'], ['daily_menus.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_details_daily_menu_id'), 'meal_details', ['daily_menu_id'], unique=False)
    op.create_index(op.f('ix_meal_details_id'), 'meal_details', ['id'], unique=False)
    op.create_index(op.f('ix_meal_details_recipe_id'), 'meal_details', ['recipe_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meal_details_recipe_id'), table_name='meal_details')
    op.drop_index(op.f('ix_meal_details_id'), table_name='meal_details')
    op.drop_index(op.f('ix_meal_details_daily_menu_id'), table_name='meal_details')
    op.drop_table('meal_details')
    op.drop_table('profiles_tastes')
    op.drop_table('profiles_restrictions')
    op.drop_index(op.f('ix_profile_eating_styles_profile_id'), table_name='profile_eating_styles')
    op.drop_index(op.f('ix_profile_eating_styles_id'), table_name='profile_eating_styles')
    op.drop_table('profile_eating_styles')
    op.drop_index(op.f('ix_daily_menus_plan_id'), table_name='daily_menus')
    op.drop_index(op.f('ix_daily_menus_id'), table_name='daily_menus')
    op.drop_table('daily_menus')
    op.drop_index(op.f('ix_recipe_meal_types_recipe_id'), table_name='recipe_meal_types')
    op.drop_index(op.f('ix_recipe_meal_types_id'), table_name='recipe_meal_types')
    op.drop_table('recipe_meal_types')
    op.drop_index(op.f('ix_recipe_diet_types_recipe_id'), table_name='recipe_diet_types')
    op.drop_index(op.f('ix_recipe_diet_types_id'), table_name='recipe_diet_types')
    op.drop_table('recipe_diet_types')
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_plans_user_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tastes_id'), table_name='tastes')
    op.drop_table('tastes')
    op.drop_index(op.f('ix_restrictions_id'), table_name='restrictions')
    op.drop_table('restrictions')
    op.drop_index(op.f('ix_recipes_id'), table_name='recipes')
    op.drop_table('recipes')
    # ### end Alembic commands ###
