"""cambio de nulos autorellnados por la bd en plans

Revision ID: 8753f2878e69
Revises: fce4bfec5690
Create Date: 2026-02-23 17:51:03.681082

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8753f2878e69'
down_revision = 'fce4bfec5690'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('plans', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('recipes', sa.Column('recipe_id', sa.Integer(), nullable=False, unique=True)),
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plans', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('recipes', 'recipe_id')
    # ### end Alembic commands ###
