"""Add test field to user

Revision ID: 9ac5dc145130
Revises: 6daad6cf0cda
Create Date: 2026-02-19 12:43:35.947230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ac5dc145130'
down_revision = '6daad6cf0cda'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test_field', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'test_field')
    # ### end Alembic commands ###
