"""Cambios not null

Revision ID: a4aa79125a09
Revises: 91593a8864a2
Create Date: 2026-02-22 09:46:20.814458

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a4aa79125a09'
down_revision = '91593a8864a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('daily_menus', 'day_of_week',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.alter_column('eating_styles', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'eating_styles', ['name'])
    
    # Eliminar la columna existente
    op.drop_column("meal_details", "schedule")
    op.add_column(
        "meal_details",
        sa.Column("schedule", sa.SmallInteger(), nullable=True)
    )

    op.alter_column('meal_details', 'status',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.alter_column('meal_details', 'meal_type',
               existing_type=postgresql.ENUM('breakfast', 'lunch', 'dinner', 'snack', name='meal_type_enum'),
               nullable=False)
    op.alter_column('plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('plans', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('plans', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('profiles', 'goal',
               existing_type=postgresql.ENUM('lose_weight', 'maintain_weight', 'gain_weight', name='goal_enum'),
               nullable=False)
    op.alter_column('profiles', 'height',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('profiles', 'weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('profiles', 'body_type',
               existing_type=postgresql.ENUM('lean', 'normal', 'stocky', 'obese', name='body_type_enum'),
               nullable=False)
    op.alter_column('profiles', 'gender',
               existing_type=postgresql.ENUM('male', 'female', name='gender_enum'),
               nullable=False)
    op.alter_column('profiles', 'meals_per_day',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.alter_column('profiles', 'activity_level',
               existing_type=postgresql.ENUM('low', 'medium', 'high', name='activity_level_enum'),
               nullable=False)
    op.alter_column('profiles', 'birth_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('recipes', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('recipes', 'calories',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('recipes', 'protein',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('recipes', 'carbs',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('recipes', 'fat',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('restrictions', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'restrictions', ['name'])
    op.alter_column('tastes', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'tastes', ['name'])
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(None, 'tastes', type_='unique')
    op.alter_column('tastes', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'restrictions', type_='unique')
    op.alter_column('restrictions', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('recipes', 'fat',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('recipes', 'carbs',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('recipes', 'protein',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('recipes', 'calories',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('recipes', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('profiles', 'birth_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('profiles', 'activity_level',
               existing_type=postgresql.ENUM('low', 'medium', 'high', name='activity_level_enum'),
               nullable=True)
    op.alter_column('profiles', 'meals_per_day',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.alter_column('profiles', 'gender',
               existing_type=postgresql.ENUM('male', 'female', name='gender_enum'),
               nullable=True)
    op.alter_column('profiles', 'body_type',
               existing_type=postgresql.ENUM('lean', 'normal', 'stocky', 'obese', name='body_type_enum'),
               nullable=True)
    op.alter_column('profiles', 'weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('profiles', 'height',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('profiles', 'goal',
               existing_type=postgresql.ENUM('lose_weight', 'maintain_weight', 'gain_weight', name='goal_enum'),
               nullable=True)
    op.alter_column('plans', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('plans', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('meal_details', 'meal_type',
               existing_type=postgresql.ENUM('breakfast', 'lunch', 'dinner', 'snack', name='meal_type_enum'),
               nullable=True)
    op.alter_column('meal_details', 'status',
               existing_type=sa.SMALLINT(),
               nullable=True)
    
    # Revertir a TIME si necesitas rollback
    op.drop_column("meal_details", "schedule")

    op.add_column(
        "meal_details",
        sa.Column("schedule", sa.Time(), nullable=True)
    )
    
    op.drop_constraint(None, 'eating_styles', type_='unique')
    op.alter_column('eating_styles', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('daily_menus', 'day_of_week',
               existing_type=sa.SMALLINT(),
               nullable=True)
    # ### end Alembic commands ###
