"""sustitucion eating_style por diet_type

Revision ID: b50bbb581adb
Revises: 5be19c140069
Create Date: 2026-02-23 12:53:29.902191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b50bbb581adb'
down_revision = '5be19c140069'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles_diet_types',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('diet_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['diet_type_id'], ['diet_types.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'diet_type_id')
    )
    op.drop_table('profiles_eating_styles')
    op.drop_index(op.f('ix_eating_styles_id'), table_name='eating_styles')
    op.drop_table('eating_styles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eating_styles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('eating_styles_pkey')),
    sa.UniqueConstraint('name', name=op.f('eating_styles_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_eating_styles_id'), 'eating_styles', ['id'], unique=False)
    op.create_table('profiles_eating_styles',
    sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('eating_style_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['eating_style_id'], ['eating_styles.id'], name=op.f('profiles_eating_styles_eating_style_id_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('profiles_eating_styles_profile_id_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'eating_style_id', name=op.f('profiles_eating_styles_pkey'))
    )
    op.drop_table('profiles_diet_types')
    # ### end Alembic commands ###
