"""Add ON DELETE and ON UPDATE constraints to all foreign keys

Revision ID: bf5ee2336f5d
Revises: 382ed2ed6d7f
Create Date: 2026-02-19 10:05:48.825667

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bf5ee2336f5d'
down_revision = '382ed2ed6d7f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('detalle_comida', 'receta_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('detalle_comida', 'menu_diario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_detalle_comida_menu_diario_id'), 'detalle_comida', ['menu_diario_id'], unique=False)
    op.create_index(op.f('ix_detalle_comida_receta_id'), 'detalle_comida', ['receta_id'], unique=False)
    op.drop_constraint(op.f('detalle_comida_menu_diario_id_fkey'), 'detalle_comida', type_='foreignkey')
    op.drop_constraint(op.f('detalle_comida_receta_id_fkey'), 'detalle_comida', type_='foreignkey')
    op.create_foreign_key(None, 'detalle_comida', 'menu_diario', ['menu_diario_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'detalle_comida', 'receta', ['receta_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.alter_column('menu_diario', 'plan_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_menu_diario_plan_id'), 'menu_diario', ['plan_id'], unique=False)
    op.drop_constraint(op.f('menu_diario_plan_id_fkey'), 'menu_diario', type_='foreignkey')
    op.create_foreign_key(None, 'menu_diario', 'plan', ['plan_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('perfil', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_perfil_usuario_id'), 'perfil', ['usuario_id'], unique=True)
    op.drop_constraint(op.f('perfil_usuario_id_fkey'), 'perfil', type_='foreignkey')
    op.create_foreign_key(None, 'perfil', 'usuario', ['usuario_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('perfil_estilo_alimentacion', 'perfil_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_perfil_estilo_alimentacion_perfil_id'), 'perfil_estilo_alimentacion', ['perfil_id'], unique=False)
    op.drop_constraint(op.f('perfil_estilo_alimentacion_perfil_id_fkey'), 'perfil_estilo_alimentacion', type_='foreignkey')
    op.create_foreign_key(None, 'perfil_estilo_alimentacion', 'perfil', ['perfil_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(op.f('perfil_gusto_perfil_id_fkey'), 'perfil_gusto', type_='foreignkey')
    op.drop_constraint(op.f('perfil_gusto_gusto_id_fkey'), 'perfil_gusto', type_='foreignkey')
    op.create_foreign_key(None, 'perfil_gusto', 'gusto', ['gusto_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'perfil_gusto', 'perfil', ['perfil_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(op.f('perfil_restriccion_perfil_id_fkey'), 'perfil_restriccion', type_='foreignkey')
    op.drop_constraint(op.f('perfil_restriccion_restriccion_id_fkey'), 'perfil_restriccion', type_='foreignkey')
    op.create_foreign_key(None, 'perfil_restriccion', 'restriccion', ['restriccion_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'perfil_restriccion', 'perfil', ['perfil_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('plan', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_plan_usuario_id'), 'plan', ['usuario_id'], unique=False)
    op.drop_constraint(op.f('plan_usuario_id_fkey'), 'plan', type_='foreignkey')
    op.create_foreign_key(None, 'plan', 'usuario', ['usuario_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('receta_tipo_comida', 'receta_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_receta_tipo_comida_receta_id'), 'receta_tipo_comida', ['receta_id'], unique=False)
    op.drop_constraint(op.f('receta_tipo_comida_receta_id_fkey'), 'receta_tipo_comida', type_='foreignkey')
    op.create_foreign_key(None, 'receta_tipo_comida', 'receta', ['receta_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('receta_tipo_dieta', 'receta_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_receta_tipo_dieta_receta_id'), 'receta_tipo_dieta', ['receta_id'], unique=False)
    op.drop_constraint(op.f('receta_tipo_dieta_receta_id_fkey'), 'receta_tipo_dieta', type_='foreignkey')
    op.create_foreign_key(None, 'receta_tipo_dieta', 'receta', ['receta_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # No changes to usuario table - existing schema  is correct
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # No changes to usuario table - existing schema is correct
    op.drop_constraint(None, 'receta_tipo_dieta', type_='foreignkey')
    op.create_foreign_key(op.f('receta_tipo_dieta_receta_id_fkey'), 'receta_tipo_dieta', 'receta', ['receta_id'], ['id'])
    op.drop_index(op.f('ix_receta_tipo_dieta_receta_id'), table_name='receta_tipo_dieta')
    op.alter_column('receta_tipo_dieta', 'receta_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'receta_tipo_comida', type_='foreignkey')
    op.create_foreign_key(op.f('receta_tipo_comida_receta_id_fkey'), 'receta_tipo_comida', 'receta', ['receta_id'], ['id'])
    op.drop_index(op.f('ix_receta_tipo_comida_receta_id'), table_name='receta_tipo_comida')
    op.alter_column('receta_tipo_comida', 'receta_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'plan', type_='foreignkey')
    op.create_foreign_key(op.f('plan_usuario_id_fkey'), 'plan', 'usuario', ['usuario_id'], ['id'])
    op.drop_index(op.f('ix_plan_usuario_id'), table_name='plan')
    op.alter_column('plan', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'perfil_restriccion', type_='foreignkey')
    op.drop_constraint(None, 'perfil_restriccion', type_='foreignkey')
    op.create_foreign_key(op.f('perfil_restriccion_restriccion_id_fkey'), 'perfil_restriccion', 'restriccion', ['restriccion_id'], ['id'])
    op.create_foreign_key(op.f('perfil_restriccion_perfil_id_fkey'), 'perfil_restriccion', 'perfil', ['perfil_id'], ['id'])
    op.drop_constraint(None, 'perfil_gusto', type_='foreignkey')
    op.drop_constraint(None, 'perfil_gusto', type_='foreignkey')
    op.create_foreign_key(op.f('perfil_gusto_gusto_id_fkey'), 'perfil_gusto', 'gusto', ['gusto_id'], ['id'])
    op.create_foreign_key(op.f('perfil_gusto_perfil_id_fkey'), 'perfil_gusto', 'perfil', ['perfil_id'], ['id'])
    op.drop_constraint(None, 'perfil_estilo_alimentacion', type_='foreignkey')
    op.create_foreign_key(op.f('perfil_estilo_alimentacion_perfil_id_fkey'), 'perfil_estilo_alimentacion', 'perfil', ['perfil_id'], ['id'])
    op.drop_index(op.f('ix_perfil_estilo_alimentacion_perfil_id'), table_name='perfil_estilo_alimentacion')
    op.alter_column('perfil_estilo_alimentacion', 'perfil_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'perfil', type_='foreignkey')
    op.create_foreign_key(op.f('perfil_usuario_id_fkey'), 'perfil', 'usuario', ['usuario_id'], ['id'])
    op.drop_index(op.f('ix_perfil_usuario_id'), table_name='perfil')
    op.alter_column('perfil', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'menu_diario', type_='foreignkey')
    op.create_foreign_key(op.f('menu_diario_plan_id_fkey'), 'menu_diario', 'plan', ['plan_id'], ['id'])
    op.drop_index(op.f('ix_menu_diario_plan_id'), table_name='menu_diario')
    op.alter_column('menu_diario', 'plan_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'detalle_comida', type_='foreignkey')
    op.drop_constraint(None, 'detalle_comida', type_='foreignkey')
    op.create_foreign_key(op.f('detalle_comida_receta_id_fkey'), 'detalle_comida', 'receta', ['receta_id'], ['id'])
    op.create_foreign_key(op.f('detalle_comida_menu_diario_id_fkey'), 'detalle_comida', 'menu_diario', ['menu_diario_id'], ['id'])
    op.drop_index(op.f('ix_detalle_comida_receta_id'), table_name='detalle_comida')
    op.drop_index(op.f('ix_detalle_comida_menu_diario_id'), table_name='detalle_comida')
    op.alter_column('detalle_comida', 'menu_diario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('detalle_comida', 'receta_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # No changes to usuario table - existing schema is correct
    # ### end Alembic commands ###
