"""Incluir relacion en taste

Revision ID: c1fab5fd59c3
Revises: aed67e279fba
Create Date: 2026-02-19 13:09:53.238669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1fab5fd59c3'
down_revision = 'aed67e279fba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'campo_prueba')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('campo_prueba', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
