"""update relationships

Revision ID: c9b51237647b
Revises: c1fab5fd59c3
Create Date: 2026-02-19 13:53:04.515130

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c9b51237647b'
down_revision = 'c1fab5fd59c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_diet_types', sa.Column('diet_type_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_recipe_diet_types_id'), table_name='recipe_diet_types')
    op.drop_index(op.f('ix_recipe_diet_types_recipe_id'), table_name='recipe_diet_types')
    op.create_foreign_key(None, 'recipe_diet_types', 'diet_types', ['diet_type_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('recipe_diet_types', 'name')
    op.drop_column('recipe_diet_types', 'id')
    op.add_column('recipe_meal_types', sa.Column('meal_type_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_recipe_meal_types_id'), table_name='recipe_meal_types')
    op.drop_index(op.f('ix_recipe_meal_types_recipe_id'), table_name='recipe_meal_types')
    op.create_foreign_key(None, 'recipe_meal_types', 'meal_types', ['meal_type_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('recipe_meal_types', 'name')
    op.drop_column('recipe_meal_types', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_meal_types', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('recipe_meal_types', sa.Column('name', postgresql.ENUM('breakfast', 'lunch', 'dinner', 'snack', name='meal_type_enum'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'recipe_meal_types', type_='foreignkey')
    op.create_index(op.f('ix_recipe_meal_types_recipe_id'), 'recipe_meal_types', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_recipe_meal_types_id'), 'recipe_meal_types', ['id'], unique=False)
    op.drop_column('recipe_meal_types', 'meal_type_id')
    op.add_column('recipe_diet_types', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('recipe_diet_types', sa.Column('name', postgresql.ENUM('high_protein', 'low_carb', 'vegan', 'vegetarian', 'low_calorie', 'high_fiber', 'high_carb', name='diet_type_enum'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'recipe_diet_types', type_='foreignkey')
    op.create_index(op.f('ix_recipe_diet_types_recipe_id'), 'recipe_diet_types', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_recipe_diet_types_id'), 'recipe_diet_types', ['id'], unique=False)
    op.drop_column('recipe_diet_types', 'diet_type_id')
    # ### end Alembic commands ###
