"""añadir campo ingredientes

Revision ID: f2098cdc0673
Revises: 8753f2878e69
Create Date: 2026-03-03 11:11:59.847030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2098cdc0673'
down_revision = '8753f2878e69'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('ingredients', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'ingredients')
    # ### end Alembic commands ###
