"""enums y cambios a modelos

Revision ID: fce4bfec5690
Revises: b50bbb581adb
Create Date: 2026-02-23 13:20:27.054024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fce4bfec5690'
down_revision = 'b50bbb581adb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("diet_types", "name",
                    existing_type=sa.Enum('high_protein', 'low_carb', 'vegan', 'vegetarian', 'low_calorie', 'high_fiber', 'high_carb', name='diet_type_enum', nullable=False),
                    type=sa.String(50))
    op.alter_column("meal_types", "name",
                    existing_type=sa.Enum('breakfast', 'lunch', 'dinner', 'snack', name='meal_type_enum', nullable=False),
                    type=sa.String(50))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("diet_types", "name",
                    existing_type=sa.String(length=50),
                    type=sa.Enum('high_protein', 'low_carb', 'vegan', 'vegetarian', 'low_calorie', 'high_fiber', 'high_carb', name='diet_type_enum'), nullable=False)
    op.alter_column("meal_types", "name",
                    existing_type=sa.String(length=50),
                    type=sa.Enum('breakfast', 'lunch', 'dinner', 'snack', name='meal_type_enum'), nullable=False)
    # ### end Alembic commands ###