"""enums y cambios a modelos

Revision ID: fce4bfec5690
Revises: b50bbb581adb
Create Date: 2026-02-23 13:20:27.054024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fce4bfec5690'
down_revision = 'b50bbb581adb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diet_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('high_protein', 'low_carb', 'vegan', 'vegetarian', 'low_calorie', 'high_fiber', 'high_carb', name='diet_type_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diet_types_id'), 'diet_types', ['id'], unique=False)
    op.create_index(op.f('ix_diet_types_name'), 'diet_types', ['name'], unique=True)
    op.create_table('meal_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('breakfast', 'lunch', 'dinner', 'snack', name='meal_type_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_types_id'), 'meal_types', ['id'], unique=False)
    op.create_index(op.f('ix_meal_types_name'), 'meal_types', ['name'], unique=True)
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('protein', sa.Integer(), nullable=False),
    sa.Column('carbs', sa.Integer(), nullable=False),
    sa.Column('fat', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('recipe_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipes_id'), 'recipes', ['id'], unique=False)
    op.create_table('restrictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_restrictions_id'), 'restrictions', ['id'], unique=False)
    op.create_table('tastes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_tastes_id'), 'tastes', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('profile_picture_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    op.create_index(op.f('ix_plans_user_id'), 'plans', ['user_id'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal', sa.Enum('lose_weight', 'maintain_weight', 'gain_weight', name='goal_enum'), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('body_type', sa.Enum('lean', 'normal', 'stocky', 'obese', name='body_type_enum'), nullable=False),
    sa.Column('body_fat_percentage', sa.Float(), nullable=True),
    sa.Column('calories_target', sa.Float(), nullable=True),
    sa.Column('protein_target', sa.Float(), nullable=True),
    sa.Column('carbs_target', sa.Float(), nullable=True),
    sa.Column('fat_target', sa.Float(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', name='gender_enum'), nullable=False),
    sa.Column('meals_per_day', sa.SmallInteger(), nullable=False),
    sa.Column('activity_level', sa.Enum('low', 'medium', 'high', name='activity_level_enum'), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=True)
    op.create_table('recipe_diet_types',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('diet_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['diet_type_id'], ['diet_types.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recipe_id', 'diet_type_id')
    )
    op.create_table('recipe_meal_types',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('meal_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meal_type_id'], ['meal_types.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recipe_id', 'meal_type_id')
    )
    op.create_table('daily_menus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_menus_id'), 'daily_menus', ['id'], unique=False)
    op.create_index(op.f('ix_daily_menus_plan_id'), 'daily_menus', ['plan_id'], unique=False)
    op.create_table('profiles_diet_types',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('diet_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['diet_type_id'], ['diet_types.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'diet_type_id')
    )
    op.create_table('profiles_restrictions',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('restriction_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restriction_id'], ['restrictions.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'restriction_id')
    )
    op.create_table('profiles_tastes',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('taste_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['taste_id'], ['tastes.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'taste_id')
    )
    op.create_table('meal_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('daily_menu_id', sa.Integer(), nullable=False),
    sa.Column('schedule', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('meal_type', sa.Enum('breakfast', 'lunch', 'dinner', 'snack', name='meal_type_enum'), nullable=False),
    sa.ForeignKeyConstraint(['daily_menu_id'], ['daily_menus.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_details_daily_menu_id'), 'meal_details', ['daily_menu_id'], unique=False)
    op.create_index(op.f('ix_meal_details_id'), 'meal_details', ['id'], unique=False)
    op.create_index(op.f('ix_meal_details_recipe_id'), 'meal_details', ['recipe_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meal_details_recipe_id'), table_name='meal_details')
    op.drop_index(op.f('ix_meal_details_id'), table_name='meal_details')
    op.drop_index(op.f('ix_meal_details_daily_menu_id'), table_name='meal_details')
    op.drop_table('meal_details')
    op.drop_table('profiles_tastes')
    op.drop_table('profiles_restrictions')
    op.drop_table('profiles_diet_types')
    op.drop_index(op.f('ix_daily_menus_plan_id'), table_name='daily_menus')
    op.drop_index(op.f('ix_daily_menus_id'), table_name='daily_menus')
    op.drop_table('daily_menus')
    op.drop_table('recipe_meal_types')
    op.drop_table('recipe_diet_types')
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_plans_user_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tastes_id'), table_name='tastes')
    op.drop_table('tastes')
    op.drop_index(op.f('ix_restrictions_id'), table_name='restrictions')
    op.drop_table('restrictions')
    op.drop_index(op.f('ix_recipes_id'), table_name='recipes')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_meal_types_name'), table_name='meal_types')
    op.drop_index(op.f('ix_meal_types_id'), table_name='meal_types')
    op.drop_table('meal_types')
    op.drop_index(op.f('ix_diet_types_name'), table_name='diet_types')
    op.drop_index(op.f('ix_diet_types_id'), table_name='diet_types')
    op.drop_table('diet_types')
    # ### end Alembic commands ###
